name: nlp2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - transformers==4.27
      - datasets
      - evaluate
      - torch
      - sacremoses
      - sacrebleu
      - bert_score
      - unbabel-comet
      - vllm
      - accelerate>=0.26.0